### PR TITLE
Feature [RR-111] tavern mini game finished

### PR DESCRIPTION
**Pull request by SzymonPiskorz**

### CODE REVIEW

**Review by MichalKrzyzanowski — APPROVED** [review]
LGTM. minigame looks like shit lmao

**Review by MichalKrzyzanowski — CHANGES_REQUESTED** [review]
NVM

**Review by BenStynes — APPROVED** [review]
LGTM

**Review by MichalKrzyzanowski — APPROVED** [review]
LGTM

**Pull request merged**
